% Convergence behaviour demo for the three proposed QPSO variants.
% The full paper workflow is implemented in run_paper_experiments.m.

clear; clc;

[summary, raw] = run_paper_experiments( ...
    'Functions', {'f1','f2','f10','f19'}, ...
    'Algorithms', {'QPSO-LR','QPSO-RM','QPSO-CS'}, ...
    'NumRuns', 30, ...
    'PopulationSize', 50, ...
    'MaxIt', 1000, ...
    'ResultsDir', fullfile(pwd, 'results_qpso_demo'), ...
    'MakePlots', true);

disp(summary);
fprintf('\nDetailed histories were saved for %d function/algorithm pairs.\n', numel(raw));
addpath('results_qpso_demo')